FROM rust:1 as build-env
WORKDIR /app
COPY employees-manager /app
COPY Cargo.toml /app
COPY Cargo.lock /app

RUN cargo build --release

FROM gcr.io/distroless/cc-debian12
COPY --from=build-env /app/target/release/employees-manager /
CMD ["./employees-manager"]