# Usa l'immagine di Node.js 20
FROM node:20-alpine as builder

# Imposta il percorso di lavoro nel container
WORKDIR /app

# Copia i file di configurazione
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il codice dell'app
COPY . .

ARG BUILD_ENVIRONMENT

# Setta la variabile d'ambiente con il valore passato dall'esterno o il valore di default
ENV BUILD_ENV=${BUILD_ENVIRONMENT}

# compila l'app
RUN npm run build:${BUILD_ENV}

# Utilizza un'immagine più leggera per il deploy
FROM nginx:alpine

# Copia il file di configurazione personalizzato in Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia i file statici compilati nell'immagine di Nginx
COPY --from=builder /app/dist/employees-manager-fe/browser /usr/share/nginx/html

# Comando di avvio
CMD ["nginx", "-g", "daemon off;"]
