FROM rust:1 as build-env
WORKDIR /app
COPY employees-manager /app/employees-manager
COPY Cargo.toml /app/Cargo.toml
COPY Cargo.lock /app/Cargo.lock

RUN cargo build --release

FROM gcr.io/distroless/cc-debian12
COPY --from=build-env /app/target/release/employees-manager /
CMD ["./employees-manager"]